# Generated by Django 6.0.3 on 2026-03-22 12:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('username', models.CharField(max_length=200, unique=True)),
                ('gameID', models.CharField(max_length=200)),
                ('scoreValue', models.IntegerField()),
                ('scoreUUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timeRecorded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
